version: '3.7'

services:
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabitmq:/etc/rabbitmq/
    networks:
      - app-network

  rest-mock:
    container_name: rest-mock
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w db.json
    ports:
      - 4000:4000
    volumes:
      - ./mocks/rest:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  rabitmq:

networks:
  app-network:
    driver: bridge
